apiVersion: v1
kind: ConfigMap
metadata:
  name: tank-ops-config
data:
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_USERNAME: postgres
  DB_PASSWORD: postgres
  DB_DATABASE: postgres
  ELASTICSEARCH_HOST: elasticsearch
  ELASTICSEARCH_PORT: "9200"