apiVersion: apps/v1
kind: Deployment
metadata:
  name: tank-ops-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tank-ops
  template:
    metadata:
      labels:
        app: tank-ops
    spec:
      containers:
        - name: tank-ops-app
          image: fugazzii/tank-ops-app:latest
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: tank-ops-config
---
apiVersion: v1
kind: Service
metadata:
  name: tank-ops-service
spec:
  selector:
    app: tank-ops
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
