version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    env_file:
      - ./.env.dev
    depends_on:
      - postgres
      - elasticsearch
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - tank-ops-network

  app_e2e:
    build:
      context: ./
      dockerfile: ./Dockerfile.e2e
    env_file:
      - ./.env.dev
    depends_on:
      - app
    networks:
      - tank-ops-network

  postgres:
    image: postgres:14.1-alpine
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - tank-ops-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
    networks:
      - tank-ops-network

  logstash:
    image: docker.elastic.co/logstash/logstash:7.15.0
    volumes:
      - ./logstash:/usr/share/logstash/pipeline
    command: logstash -f /usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch
      - postgres
    networks:
      - tank-ops-network

networks:
  tank-ops-network:

volumes:
  postgres:
  elasticsearch: